'use strict';
let report;
const $=id=>document.getElementById(id);
const names={piecewise_hazard:'Piecewise hazard',global_median:'Pooled median (KM)',priority_median:'Priority median (KM)'};
const fields={priority:'Priority',contact_type:'Contact type',category:'Category',weekday:'Observation weekday',hour_band:'Observation hour',age_band:'Age when first observed'};
const week=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
function scenario(){return Object.fromEntries(Object.keys(fields).map(k=>[k,$(k).value]));}
function baseline(candidate,row){return candidate==='global_median'?report.model.global_km:(report.model.priority_km[row.priority]||report.model.global_km);}
function survival(candidate,row,time){
 if(candidate!=='piecewise_hazard'){let value=1;for(const [t,s] of baseline(candidate,row)){if(t<=time)value=s;else break;}return value;}
 let hazard=0;const m=report.model;
 for(let i=0;i<m.bins.length-1;i++){const length=Math.min(time,m.bins[i+1])-m.bins[i];if(length<=0)break;let log=m.intercept;for(const [key,value] of Object.entries({...row,interval:String(i)}))log+=m.coefficients[key+'='+value]||0;hazard+=Math.exp(Math.max(-30,Math.min(10,log)))*length;}
 return Math.exp(-hazard);
}
function med(candidate,row){if(candidate!=='piecewise_hazard')return baseline(candidate,row).find(point=>point[1]<=.5)?.[0]??null;if(survival(candidate,row,168)>.5)return null;let lo=0,hi=168;for(let i=0;i<32;i++){const mid=(lo+hi)/2;if(survival(candidate,row,mid)>.5)lo=mid;else hi=mid;}return hi;}
function node(name,attrs={}){const el=document.createElementNS('http://www.w3.org/2000/svg',name);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,String(v)));return el;}
function cell(row,text){const td=document.createElement('td');td.textContent=text;row.append(td);}
function draw(candidate,row){const svg=node('svg',{viewBox:'0 0 650 280',role:'img','aria-label':'Estimated probability of remaining unresolved through seven days'});const x=t=>55+t/168*565,y=s=>235-s*210;for(const value of [0,.25,.5,.75,1]){svg.append(node('line',{x1:55,x2:620,y1:y(value),y2:y(value),stroke:'#dfe8e1'}));const t=node('text',{x:45,y:y(value)+4,'text-anchor':'end'});t.textContent=Math.round(value*100)+'%';svg.append(t);}const points=[];for(let t=0;t<=168;t+=2)points.push(x(t)+','+y(survival(candidate,row,t)));svg.append(node('polyline',{points:points.join(' '),fill:'none',stroke:'#287466','stroke-width':3}));for(const time of [0,24,72,168]){const text=node('text',{x:x(time),y:265,'text-anchor':'middle'});text.textContent=time+' h';svg.append(text);}$('chart').replaceChildren(svg);}
function render(){const row=scenario(),candidate=$('candidate').value,median=med(candidate,row);$('p24').textContent=((1-survival(candidate,row,24))*100).toFixed(1)+'%';$('p168').textContent=((1-survival(candidate,row,168))*100).toFixed(1)+'%';$('median').textContent=median===null?'Beyond 7 days':median.toFixed(1)+' h';draw(candidate,row);ChartKit.survival(candidate,row,survival,report);$('priorities').replaceChildren();for(const [priority,results] of Object.entries(report.test_by_priority)){const v=results[candidate],tr=document.createElement('tr');[priority,v.n,v.resolved_within_168h,v.censored_before_168h,v.mean_ipcw_brier??'Not estimable',v.observed_event_median_mae_hours===null?'—':v.observed_event_median_mae_hours+' h'].forEach(value=>cell(tr,value));$('priorities').append(tr);}}
function select(id,label,values){const holder=document.createElement('label');holder.textContent=label;const input=document.createElement('select');input.id=id;for(const value of values){const option=document.createElement('option');option.value=value;option.textContent=id==='weekday'?week[Number(value)]:id==='hour_band'?`${String(Number(value)*6).padStart(2,'0')}:00–${String(Number(value)*6+5).padStart(2,'0')}:59`:id==='candidate'?names[value]:value;input.append(option);}input.addEventListener('change',render);holder.append(input);$('inputs').append(holder);}
async function load(){try{const response=await fetch('model-report.json',{cache:'no-store'});if(!response.ok)throw new Error('Unavailable');report=await response.json();for(const [key,label] of Object.entries(fields))select(key,label,report.model.support[key]);select('candidate','Compare model',Object.keys(names));$('candidate').value=report.selected_model;if(report.model.support.priority.includes('3 - Moderate'))$('priority').value='3 - Moderate';if(report.model.support.contact_type.includes('Phone'))$('contact_type').value='Phone';$('loading').hidden=true;$('content').hidden=false;for(const [name,value] of Object.entries(report.test)){const row=document.createElement('tr');[names[name]+(name===report.selected_model?' ✓':''),value.mean_ipcw_brier,value.observed_event_median_mae_hours+' h'].forEach(v=>cell(row,v));$('comparison').append(row);}$('result-note').textContent='Selected on earlier validation: '+names[report.selected_model]+'. Test cases: '+report.cohort.test_n+'. Lower probability error is better; it is not percent accuracy.';$('cohort').textContent=`Training: ${report.cohort.training_n} first observations, February–March 2016; labels stop March 31. Validation: ${report.cohort.validation_n} April 1–14 origins with observations through April 30. Test: ${report.cohort.test_n} May 1–14 origins with observations through May 31. No incident appears in two splits.`;report.limitations.forEach(text=>{const li=document.createElement('li');li.textContent=text;$('limitations').append(li);});$('drift').textContent='Training-to-test feature drift (total variation; 0 means no change): '+Object.entries(report.drift).map(([k,v])=>`${k}: ${v.total_variation}; unseen fraction ${v.unseen_test_fraction}`).join(' · ');$('version').textContent='Model version '+report.version+' · Artifact generated '+new Date(report.generated_at).toLocaleString();render();}catch(error){$('loading').textContent='The model could not be loaded. Please retry later.';}}
$('download').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='resolution-model-evaluation.json';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});load();
